spring.application.name=stockpro-api
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=stockpro;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}